"A"|asc|print;
"G"|bool|print; 
""|bool|print; 
"5.67"|float|print; 
"5"|int|print; 
"0123456789"|length|print; 
"HELLO"|lower|print; 
"   HELLO"|ltrim|print; 
"Hello"|print; 
"HELLO   "|rtrim|print; 
"   HELLO   "|str|print; 
"   HELLO   "|trim|print; 
"hello"|upper|print; 
